# This is used by repo2docker. conda can install all the Jupyter dependencies.

name: jyve-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - flake8
  - geckodriver
  - jupyterlab >=0.34,<0.35
  - nodejs >=8.9.3,<9
  - python >=3.6,<3.7
  - python-chromedriver-binary
  - robotframework-lint
  - robotframework-seleniumlibrary
  - selenium =3.8.0
  - wget
  - pip:
      - beautysh
