# This is used by repo2docker. conda can install all the Jupyter dependencies.

name: jyve-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - beautysh
  - flake8
  - geckodriver
  - jupyterlab >=0.35,<0.36
  - nodejs >=8.12,<9
  - python >=3.7,<3.8
  - python-chromedriver-binary
  - robotframework-lint
  - robotframework-seleniumlibrary
  - selenium >=3.14, <3.15
  - wget
